version: '3.7'
services:
  learn-prisma-postgres:
    container_name: learn-prisma-postgres
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - learn-prisma-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: learn-prisma-postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"

volumes:
  learn-prisma-postgres:
    driver: local
